server:
  tomcat:
    accept-count: 50
    max-threads: 200
    max-connections: 6000

web:
  upload-path:  D:/file/uj/
spring:
  zipkin:
    base-url: http://59.110.164.54:9411
    #本项目服务名
    service:
      name: ${spring.application.name}
    locator:
      discovery:
        enabled: true
    sender:
      type: web
  sleuth:
   #监控开关
    enabled: true
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 139.224.195.76
    port: 5672
    username: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
    password: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
# 开启发送确认
    publisher-confirms: true
# 开启发送失败退回
    publisher-returns: true
# 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    #host: ENC(ttbY+nvTWlPDb05Vsi6wqlliA6FwSJ8U)
    host: 139.224.195.76
    #port: ENC(O3fcsNa6YHqID8/XmldBQA==)
    port: 16379
    password: ENC(e6SUa4HUSLkj3dnRmFQbGkQyFH6aSjlV)
    timeout: 0
    pool:
      max-wait: 5000
      max-active: 10000
      max-idle: 50
      min-idle: 10
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 100Mb
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization: 
      write-dates-as-timestamps: false
logging:
  level: 
    root: debug
    com:
      cj: debug
mybatis:
  type-aliases-package: com.cj.common.entity
  mapper-locations: classpath:com/cj/common/mapper/*.xml
tx-lcn:
  client:
    manager-address: ENC(vdESOQXZYndFhdFY850ckoFraCHljumdLNGTr1Z+hkM=)
    tm-rpc-timeout: 2000
ribbon:
#ribbon请求连接的超时时间，限制5秒内必须请求到服务，并不限制服务处理的返回时间
  ConnectTimeout: 10000
#   SocketTimeout: 60000
  #请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout
  ReadTimeout: 60000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对当前实例的重试次数
  MaxAutoRetries: 0
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1
