spring:
  datasource:
    url: jdbc:mysql://139.224.195.76:63306/ujiev2_1_test?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ENC(9aNi3IHj2H6kZr0ODNHtyA==)
    password: ENC(TkOCIol7cpFd41MfpYYQBK+giiV3zOn3)
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#该参数用来开启重试机制，默认是关闭
  cloud:
    loadbalancer:
      retry:
        enabled: true
zuul:
  addProxyHeaders: true
  routes:
    s-zuul:
      path: /s-zuul/**

    s-file:
      path: /s-file/**
    s-im:
      path: /s-im/**

    s-admin:
      path: /s-admin/**
    s-user:
      path: /s-user/**
    s-basic:
      path: /s-basic/**
    s-consult:
      path: /s-consult/**
    s-pension:
      path: /s-pension/**
    s-kidney:
      path: /s-kidney/**

#    api-c:
#      path: /s-file/api/**
#      serviceId: s-file
#      stripPrefix: false

  #传播到其他服务
  sensitive-headers:  Cookie,Set-Cookie,Authorization
  ignored-headers:  Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  strip-prefix: true
#  ignored-patterns: '*'
  #重试
  retryable: false
  ribbon-isolation-strategy: thread
  #zuul超时设置
  host:
    socket-timeout-millis: 2000
    connect-timeout-millis: 4000
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        timeout:
          enabled: true
      circuitBreaker:
        requestVolumeThreshold: 5000
        sleepWindowInMilliseconds: 2000
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
          semaphore:
            maxConcurrentRequests: 2000


datapram:
  tooldir: mysqldump
  ip: 118.123.16.211
  dbname: ujie
  username: ENC(9aNi3IHj2H6kZr0ODNHtyA==)
  password: ENC(TkOCIol7cpFd41MfpYYQBK+giiV3zOn3)
  dir: D:/file/uj/sql/
